packages:
  - example

catalog:
  "@tsconfig/node24": ^24.0.4
  "@types/node": 24.10.3
  "@vitejs/plugin-vue": ^6.0.3
  "@vue/tsconfig": ^0.8.1
  typescript: ~5.9.3
  v-custom-block: ^1.0.67
  vite: 8.0.0-beta.14
  vue: ^3.5.28
  vue-router: ^5.0.2
  vue-tsc: ^3.2.4
  sass: ^1.97.3
