packages:
  - packages/*
  - example

catalog:
  '@vitejs/plugin-vue': ^6.0.2
  '@vue/tsconfig': 0.8.1
  'typescript': 5.9.3
  '@tsconfig/node24': ^24.0.3
  '@types/node': 24.10.3
  'v-custom-block': ^1.0.67
  'vue': 3.5.25
  'vue-router': ^4.6.3
  'vue-tsc': ^3.1.5
  'vite': ^7.2.7
