packages:
  - example

catalog:
  "@tsconfig/node24": ^24.0.4
  "@types/node": 25.7.0
  "@vitejs/plugin-vue": ^6.0.6
  "@vue/tsconfig": ^0.9.1
  typescript: ~6.0.3
  v-custom-block: ^1.0.67
  vite: 8.0.12
  vue: ^3.5.34
  vue-router: ^5.0.6
  vue-tsc: ^3.2.8
